CREATE TABLE inscricoes(
id INTEGER PRIMARY KEY AUTOINCREMENT,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
telefone VARCHAR(20) NOT NULL,
data_nascimento DATE NOT NULL,
genero VARCHAR(10) NOT NULL,
tipo_inscricao VARCHAR(30) NOT NULL,
senha VARCHAR(255) NOT NULL,
mensagem VARCHAR(200) NOT NULL,
data_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

SELECT * FROM inscricoes;